apiVersion: apps/v1
kind: Deployment

metadata:
  name: speech-query-api-deployment
  #namespace: aks
  labels:
    version: 1.0.0
    product: speech-http-query-api
    environment: aks

spec:
  replicas: 1
  selector:
    matchLabels:
      app: speech-http-query-api
      env: aks
  template:
    metadata:
      labels:
        app: speech-http-query-api
        env: aks
    spec:
      containers:
      - name: speech-http-query-api
        image: logcornerhub/logcorner-edusync-speech-query
        imagePullPolicy: IfNotPresent
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Kubernetes.aks"
        ports:
        - containerPort: 80
        - containerPort: 443
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      imagePullSecrets:
       - name: regsecret 
    