apiVersion: v1
kind: Service
metadata:
  #namespace: aks
  name: speech-http-query-api-service
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    version: 1.0.0
    product: speech-http-query-api
    environment: aks
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app: speech-http-query-api
    env: aks