apiVersion: v1
kind: Service
metadata:
  name: query-api-deployment
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    run: query-api