version: '3.4'

services:
  logcorner.edusync.speech.presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8082:80"
    networks:
      - my_network
networks:
  my_network:
    external:
      name: my_network   