version: '3.4'

services:
  logcorner.edusync.speech.query:
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8082:80"
    networks:
      - speech_network
networks:
  speech_network:
    external:
      name: speech_network   